FROM node:14.17-alpine AS build
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1-alpine
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY --from=build /app/dist/letscode-kanban /usr/share/nginx/html

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf" && nginx -g 'daemon off;'